"""initial

Revision ID: 0d6476485dd5
Revises: 
Create Date: 2024-04-12 19:11:53.917623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6476485dd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('short_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('invite_link', sa.String(length=64), nullable=False),
    sa.Column('bdayer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('users_added', sa.Integer(), nullable=False),
    sa.Column('users_invited', sa.Integer(), nullable=False),
    sa.Column('participated', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bdayer_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('invite_link')
    )
    op.create_table('bank_accounts',
    sa.Column('link', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('used_in', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['used_in'], ['chats.chat_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
