"""extended chat table

Revision ID: 3bf7ba21fa50
Revises: 0d6476485dd5
Create Date: 2024-04-13 17:26:28.587625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf7ba21fa50'
down_revision: Union[str, None] = '0d6476485dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('bdayer_last_name', sa.String(length=64), nullable=True))
    op.add_column('chats', sa.Column('account_link', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'account_link')
    op.drop_column('chats', 'bdayer_last_name')
    # ### end Alembic commands ###
