"""added notification columns

Revision ID: 4292a8985146
Revises: e32505f6ed32
Create Date: 2024-04-14 15:17:53.664889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4292a8985146'
down_revision: Union[str, None] = 'e32505f6ed32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('notification_birthday_sent', sa.Boolean(), nullable=False))
    op.add_column('chats', sa.Column('notification_deletion_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'notification_deletion_sent')
    op.drop_column('chats', 'notification_birthday_sent')
    # ### end Alembic commands ###
