"""renamed bdayer_last_name to chat_title

Revision ID: e32505f6ed32
Revises: 3bf7ba21fa50
Create Date: 2024-04-13 17:45:42.204664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e32505f6ed32'
down_revision: Union[str, None] = '3bf7ba21fa50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_title', sa.String(length=64), nullable=True))
    op.drop_column('chats', 'bdayer_last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('bdayer_last_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('chats', 'chat_title')
    # ### end Alembic commands ###
